version: 0.2

phases:
  install:
    commands:
      - echo "No dependencies to install."  
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - echo Building the project...
      # Add your build commands here if needed
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Uploading build artifacts to S3...
      - aws s3 cp ./project-1-Nicolehdz/ s3://csce412nhernandez-bucket/project-1-Nicolehdz/ --recursive
artifacts:
  files:
    - '**/*'
